postgres:
  datasource:
    driver—class—name: org.postgresql.Driver
    username: postgres
    password: root
    jdbc-url: jdbc:postgresql://localhost:5432/postgres

mysql:
  datasource:
    driver—class—name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    jdbc-url: jdbc:mysql://localhost:3306/mydb